### ISSUE TITLE
Bug - Bound Patcher Loses Correct Typings

### ISSUE THREAD

**Issue by Neodymium7** [Zerthox/betterdiscord-types#1]
The Patcher methods on a bound instance of BdApi lose their proper typings, likely because the `Bound` type used to create the bound patcher doesn't retain the methods' generics.

With `BdApi.Patcher.after`:

![image](https://user-images.githubusercontent.com/68879269/200140624-6755037d-4df6-451b-a0ae-b049537a193a.png)

With `new BdApi("Caller").Patcher.after` and the same arguments passed without the caller:

![image](https://user-images.githubusercontent.com/68879269/200140660-8349aa81-6bd0-44ad-9086-6928fe5def27.png)

I've been playing around with trying to find some solutions, but the only thing that's worked so far is just redefining the patcher without the `caller` argument in its methods. There might be a more creative solution, but I haven't been able to find one.

**Comment by Zerthox** [comment]
Adding a constraint to the module type parameter seems to help, but we'd still be losing the generics on the bound Patcher. Manually typing a bound version might be the better choice here.

**Comment by Neodymium7** [comment]
Yep, that seems to fix the issue, thanks!

Random sidenote: Do you mind if I used this as a dependency in the next version of my [plugin bundler](https://github.com/Neodymium7/BundleBD)?

**Comment by Zerthox** [comment]
Sure, go ahead.
