### ISSUE TITLE
ContextMenu.patch callback cannot accept props argument

### ISSUE THREAD

**Issue by Neodymium7** [Zerthox/betterdiscord-types#3]
Patching a context menu like shown below results in an error, as the ContextMenuCallback type cannot have a `props` argument, even though I believe the props [are passed to the patch callback](https://github.com/BetterDiscord/BetterDiscord/blob/main/renderer/src/modules/api/contextmenu.js#L121).
```ts
BdApi.ContextMenu.patch("guild-context", (ret, props) => {
    console.log(props);
});
```
![image](https://user-images.githubusercontent.com/68879269/200480192-87279cbb-0a1d-4bb4-9623-92b751e6dca6.png)

**Comment by Zerthox** [comment]
Thanks for reporting. Looks like yet another part where the BD docs are incomplete. They don't mention the 2nd argument.
