### ISSUE TITLE
addStyle and removeStyle expect 1 argument less than they should

### ISSUE THREAD

**Issue by devicarus** [Zerthox/betterdiscord-types#8]
Hi, I'm having an issue with the `DOM.addStyle` and `DOM.removeStyle` methods, for some reason they expect 1 argument less than they should?
```
src/index.tsx:15:37 - error TS2554: Expected 1 arguments, but got 2.
15     this.bdApi.DOM.addStyle('test', `random css`);
                                       ~~~~~~~~~~~~

src/index.tsx:20:32 - error TS2554: Expected 0 arguments, but got 1.
20     this.bdApi.DOM.removeStyle('test');
```

**Comment by Zerthox** [comment]
This is intended, because `id` is  bound to the caller name passed in `new BdApi`. However, it seems that contrary to other APIs that get bound to the caller name `addStyle` and `removeStyle` support passing a custom `id` to override the set caller name.

**Comment by Zerthox** [comment]
Fixed in https://github.com/Zerthox/betterdiscord-types/commit/239c1c1b01a5c041868a285ba46658c4aaebf07c.
